services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db 
    ports:
      - "33061:3306"
        # MYSQL = 3306 포트번호
      
